SELECT CITY, LENGTH(CITY)
FROM STATION 
WHERE LENGTH(CITY) IN (SELECT MAX(LENGTH(CITY)) FROM STATION) 
ORDER BY CITY;

SELECT CITY, LENGTH(CITY)
FROM STATION 
WHERE LENGTH(CITY) IN (SELECT MIN(LENGTH(CITY)) FROM STATION) 
ORDER BY CITY LIMIT 1;




SELECT CITY, LENGTH(CITY)
FROM STATION 
ORDER BY LENGTH(CITY), CITY LIMIT 1;

SELECT CITY, LENGTH(CITY)
FROM STATION 
ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;
